openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost
paths:
  /watches:
    post:
      summary: Upload Watch information
      operationId: createWatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Watch'
        required: true
      responses:
        "200":
          description: OK
components:
  schemas:
    Watch:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        price:
          type: integer
          format: int32
        description:
          type: string
        fountain:
          type: string
